# Generated by Django 5.1.1 on 2024-10-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=150)),
                ("message", models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="news", options={"ordering": ["-pulished_time"]},
        ),
    ]
