# Generated by Django 4.2.6 on 2024-10-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0002_contact_alter_news_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="surename",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
